[tool.poetry]
name = "lmu-settings-widget"
version = "0.6.3"
description = ""
authors = ["Stefan Tapper <tapper.stefan@gmail.com>"]
readme = "README.md"
packages = [{include = "lmu", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
eel = "^0.17.0"
bottle = "^0.13.2"
appdirs = "^1.4.4"
# PyGame 2.5.2 (SDL 2.28.3, Python 3.11.0) will not detect Joysticks with only axis (eg. Pedals) likely related
# to a bug in SDL https://github.com/pygame/pygame/issues/2932
# 2.4.0 (SDL 2.26.4, Python 3.11.0) works
pygame = "==2.4.0"
psutil = "6.1.0"
gevent-websocket = "==0.10.1"
gevent = "^24.10.2"
lxml="*"


[tool.poetry.group.dev.dependencies]
pyinstaller = "^6.9.0"
pyinstaller-hooks-contrib = ">=2024.7"
pywin32-ctypes = ">=0.2.0"
pytest = "^8.3.3"
black = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
